services:
    app:
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./src/:/var/www/html
        depends_on:
            - nginx

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./src/:/var/www/html
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
